

set :user, 'ubuntu'
task :setup do
  # Update the packages
  run "#{sudo} aptitude update"
  run "#{sudo} aptitude full-upgrade -y"

  # Setup the PPAs
  run "#{sudo} aptitude install -y python-software-properties"
  run "#{sudo} apt-add-repository ppa:motumedia/ppa"
  run "#{sudo} aptitude update"

  # ffmpeg
  run "#{sudo} aptitude install -y ffmpeg"
end
