#! /bin/sh
### BEGIN INIT INFO
# Provides:          flumotion
# Required-Start:    $local_fs $remote_fs
# Required-Stop:     $local_fs $remote_fs
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Flumotion Streaming Server
# Description:       Flumotion is a streaming server for audio and video.
#                    See http://www.fluendo.com for details.
### END INIT INFO

# Author: Loic Minier <lool@dooz.org>

# Do NOT "set -e"

# PATH should only include /usr/* if it runs after the mountnfs.sh script
PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
DESC="Flumotion Streaming Server"
NAME="flumotion"
LOGFILE="/usr/local/var/log/flumotion/service.log"
DAEMON="/usr/local/sbin/$NAME"
DAEMON_ARGS="-d 3 -l $LOGFILE"
SCRIPTNAME="/etc/init.d/$NAME"

# Exit if the package is not installed
[ -x "$DAEMON" ] || (echo "$DAEMON not executable"; exit 0)

# Read configuration variable file if it is present
[ -r "/etc/default/$NAME" ] && . "/etc/default/$NAME"

# Load the VERBOSE setting and other rcS variables
[ -f /etc/default/rcS ] && . /etc/default/rcS
VERBOSE=yes

# Define LSB log_* functions.
# Depend on lsb-base (>= 3.0-6) to ensure that this file is present.
. /lib/lsb/init-functions

user_do() {
	# set an umask for log files
	# unset HOME as otherwise flumotion uses $HOME/.flumotion as its cache
	# dir
	su -s /bin/sh -c "umask 026; unset HOME; $1" flumotion
	return "$?"
}

#
# Function that starts all instances
#
do_start()
{
	# Return
	#   0 if all instances could be started
	#   1 if one or more instances could not be started
	if [ "x$*" != "x" ]; then
		start_instance $*
		return "$?"
	fi
	list="`user_do "$DAEMON status" | cut -f1,2 -d' ' | tr ' ' @`"
	RETVAL="0"
	for line in $list; do
		type="`echo "$line" | cut -f1 -d'@'`"
		name="`echo "$line" | cut -f2 -d'@'`"
		start_instance "$type" "$name" || RETVAL=1
	done
	return "$RETVAL"
}

start_instance() {
	type="$1"
	name="$2"
	user_do "$DAEMON $DAEMON_ARGS start $type $name"
	return "$?"
}

#
# Function that stops all instances
#
do_stop()
{
	# Return
	#   0 if all instances could be stopped
	#   1 if one or more instances could not be stopped
	if [ "x$*" != "x" ]; then
		stop_instance $*
		return "$?"
	fi

	list="`user_do "$DAEMON status" | cut -f1,2 -d' ' | tr ' ' @`"
	RETVAL="0"
	for line in $list; do
		type="`echo $line | cut -f1 -d'@'`"
		name="`echo $line | cut -f2 -d'@'`"
		stop_instance "$type" "$name" || RETVAL=1
	done
	return "$RETVAL"
}

stop_instance() {
	type="$1"
	name="$2"
	user_do "$DAEMON $DAEMON_ARGS stop $type $name"
	return "$?"
}

do_status() {
	user_do "$DAEMON status"
	echo
	flumotion-command component detailedlist
	echo
	components=`flumotion-command component list`
	for comp in $components;
	do
		if [ $comp == "atmosphere:" ]; then
			flow="atmosphere"
		elif [ $comp == "default" -o $comp == "flow:" ]; then
			flow="default"
		else
			flumotion-command component -i /$flow/$comp mood
		fi
	done
}

do_clean() {
	user_do "$DAEMON clean"
}

do_list() {
	user_do "$DAEMON list"
}

# Create flumotion's home dir on startup as it might be a tmpfs
if [ ! -d /usr/local/var/run/flumotion ]; then
	mkdir -p /usr/local/var/run/flumotion
	chown -R flumotion:flumotion /usr/local/var/run/flumotion
fi
if [ ! -d /usr/local/var/cache/flumotion ]; then
	mkdir -p /usr/local/var/cache/flumotion
	chown -R flumotion:flumotion /usr/local/var/cache/flumotion
fi
if [ ! -d /usr/local/var/log/flumotion ]; then
	mkdir -p /usr/local/var/log/flumotion
	chown -R flumotion:flumotion /usr/local/var/log/flumotion
fi
if [ -e $LOGFILE ]; then
	chown -R flumotion:flumotion $(dirname $LOGFILE)
fi

function do_components {
	set -e
	components=`flumotion-command component list`

	for comp in $components;
	do
		if [ $comp == "atmosphere:" ]; then
			flow="atmosphere"
		elif [ $comp == "default" -o $comp == "flow:" ]; then
			flow="default"
		else
			while flumotion-command component -i /$flow/$comp mood | grep waking >/dev/null; do
				sleep 1
			done
			flumotion-command component -i /$flow/$comp $1 >/dev/null
		fi
	done
}

case "$1" in
  start)
	shift
	[ "$VERBOSE" != no ] && log_daemon_msg "Starting $DESC" "$NAME"
	do_start $*
	case "$?" in
		0|1) [ "$VERBOSE" != no ] && log_end_msg 0 ;;
		2) [ "$VERBOSE" != no ] && log_end_msg 1 ;;
	esac

	[ "$COMPONENTS" = stopped ] && /etc/init.d/flumotion stop-components
	;;
  stop)
	shift
	[ "$VERBOSE" != no ] && log_daemon_msg "Stopping $DESC" "$NAME"
	do_stop $*
	case "$?" in
		0|1) [ "$VERBOSE" != no ] && log_end_msg 0 ;;
		2) [ "$VERBOSE" != no ] && log_end_msg 1 ;;
	esac
	;;
  start-components)
	shift
	[ "$VERBOSE" != no ] && log_daemon_msg "Starting components" "$NAME"
	do_components start
	case "$?" in
		0|1) [ "$VERBOSE" != no ] && log_end_msg 0 ;;
		2) [ "$VERBOSE" != no ] && log_end_msg 1 ;;
	esac
	;;
  stop-components)
	shift
	[ "$VERBOSE" != no ] && log_daemon_msg "Stopping $NAME components"
	do_components stop
	case "$?" in
		0|1) [ "$VERBOSE" != no ] && log_end_msg 0 ;;
		2) [ "$VERBOSE" != no ] && log_end_msg 1 ;;
	esac
	;;
  restart|force-reload)
	shift
	[ "$VERBOSE" != no ] && log_daemon_msg "Restarting $DESC" "$NAME"
	do_stop $*
	do_start $*
	case "$?" in
		0) [ "$VERBOSE" != no ] && log_end_msg 0 ;;
		1) [ "$VERBOSE" != no ] && log_end_msg 1 ;; # Old process is still running
		*) [ "$VERBOSE" != no ] && log_end_msg 1 ;; # Failed to start
	esac

	[ "$COMPONENTS" = stopped ] && /etc/init.d/flumotion stop-components
	;;
  status)
	do_status
	;;
  clean)
	do_clean
	;;
  list)
	do_list
	;;
  *)
	echo "Usage: $SCRIPTNAME {start|stop|restart|force-reload|status|clean|list}" >&2
	exit 3
	;;
esac

:
